- docs/pages/api_reference.mdx
This PR fixes broken/dead links in the `api_reference.mdx` file found at the page for [API Reference](https://labs.convex.dev/auth/api_reference) in the docs. 
----
> Fix broken links in api_reference.mdx

- docs/pages/api_reference.mdx
- docs/pages/authz.mdx
- docs/pages/config/email.mdx
- docs/pages/config/oauth.mdx
This PR fixes some broken links in the documentation. I wasn't able to test it locally (running into a build error) but the fixes are simple and I've double-checked the URLs.
> Fix broken links

- src/nextjs/server/cookies.ts
See https://github.com/get-convex/convex-auth/issues/60 -- the alternative approach would be to make this a flag that's passed in + a note for Safari users to turn this on instead of doing this automatically.
> Don't use secure: true cookies for localhost

- src/nextjs/server/index.tsx
- src/nextjs/server/proxy.ts
Surfaced [here](https://discord.com/channels/1019350475847499849/1281663493648547905). Matching both seems fairly harmless.
> Match with and without trailing slash in Next.js middleware

- src/nextjs/server/index.tsx
- src/nextjs/server/request.ts
- src/nextjs/server/utils.ts
I was able to reproduce [this bug](https://discord.com/channels/1019350475847499849/1279823393125961748) whenever the client failed to proactively fetch the new access token before it expired, and the server ended up fetching a new token instead.
We'd successfully fetch the token on the server, but we weren't consistently propagating it on to the next handler, which meant that SSR that relied on auth would be reading a stale value.
In particular, I think we should never be calling `NextResponse.next()` until we've mutated our request to reflect any auth we've fetched on the server.
> [Next.js] Propagate auth cookies in request to subsequent handlers in middleware

- docs/pages/api_reference/nextjs/server.mdx
- docs/pages/authz/nextjs.mdx
- src/nextjs/server/index.tsx
- test-nextjs/middleware.ts
Follow up to [this PR](https://github.com/get-convex/convex-auth/pull/70).
I wasn't propagating these headers properly in all places. Notably, for the handler passed in to `convexAuthNextjsMiddleware`, while the `request` passed in will have headers that reflect any updated cookies, `headers()` and `cookies()` from `next/headers` will not.
So if we refetch tokens as part of a request, we won't read those new values (or lack of values if refetching failed) in the handler. One way of producing buggy behavior was by having an expired token + invalid refresh token, where instead of the middleware clearing cookies and redirecting to sign in (because it can't fetch a new token), it would attempt to render the page and error.
We want `convexAuthNextjsToken()` and `isAuthenticatedNextjs()` to be …
> [Next.js] Propagate auth cookies in middleware (take 2)

- docs/pages/api_reference/nextjs/server.mdx
This pull request fixes a documentation issue where a TypeScript code block was not properly closed with the correct ``` syntax. This caused formatting problems on the rendered page.
The changes made ensure that the code is properly formatted and displayed as TypeScript. 
No functional code changes were made; this is strictly a documentation fix.
----
> fix: close unclosed TypeScript code block

- src/server/implementation/mutations/refreshSession.ts
- src/server/implementation/refreshTokens.ts
- src/server/implementation/sessions.ts
- src/server/implementation/types.ts
- test/convex/sessions.test.ts
Without this diff, refresh tokens are single use. This can be problematic for Next.js where two requests can race each other and use the same refresh token, resulting in one of them failing + invalidating the entire session.
The example I was testing with was loading the same app twice in two separate tabs, with some injected latency to make them actually race. One tab would lose the race to use the refresh token, and result in clearing out the cookies for both tabs and not so gracefully logging out.
With the 10s window for reuse, when two requests race, both will end up receiving tokens (in this implementation, they're different, but I don't think it matters), so both tabs will stay logged in. A refresh token will live in the database until the next token exchange for the session. …
> Add 10s reuse window for refresh tokens

- src/nextjs/server/proxy.ts
- src/react/client.tsx
- src/server/implementation/index.ts
`signIn` references the type `Tokens` that wasn't exported (reported [here](https://discord.com/channels/1019350475847499849/1286561479247794206/1286561479247794206)).
This adds an explicit type annotation + exports the type referenced. The type annotation is a little broader than necessary (in my ideal world, this would return a discriminated union so we could type narrow). There were a couple spots where I had to assert that `result.verifier` was defined when `result.redirect` was defined, which is clear from reading the code but not clear from the type.
> Export type referenced in signIn + fix downstream errors

- src/nextjs/server/proxy.ts
If talking to Convex fails for any reason (even though it shouldn't), I believe we end up sending a 500 with a generic Next.js error and fail to reset any state (i.e. clear cookies).
I've witnessed this hitting an error refreshing the session, and instead of clearing the cookies, we error and the client continues to have a useless refresh token in its cookies.
This also fixes an issue where we were requiring a valid auth token for `signIn`, when really we should just require one for `signOut`
> Gracefully handle errors thrown during /api/auth

- src/server/implementation/index.ts
- src/server/implementation/signIn.ts
This is part 1 of 2. I want to be able to see which functions are called from the ConvexReactClient vs. called from Next.js requests. I added this as optional, will do a release, and then will do another release where I start passing it in, so folks who care about version skew can upgrade in 2 stages if they want.
Other things I considered but did not do:
* Stick this in `params` and remove it in `signInImpl` -- seemed a little too gross + would squat on a potential param that a developer could use.
* Propagate this to `auth:store` calls -- I think the Convex request ID should be good enough to link things together there.
> Add optional calledBy + logging for signIn action

- docs/pages/api_reference/nextjs/server.mdx
- docs/pages/api_reference/server.mdx
- docs/pages/authz.mdx
- docs/pages/config.mdx
- docs/pages/config/oauth.mdx
- docs/pages/faq.mdx
- docs/pages/index.mdx
- docs/pages/setup.mdx
- docs/pages/setup/manual.mdx
- src/nextjs/server/index.tsx
Changes included in here:
* Remove references to anonymous auth because I believe we launched without this
* Recommend Github, Google, and Apple as OAuth providers we know work with Convex Auth, and soften the claim that we work with any Auth.js OAuth provider.
* Add a note in the FAQ that we currently just have the client library for React
* Add a note that Next.js SSA support is experimental -- I'm down to say "beta" too, but given that we're still pretty actively squashing bugs here, "experimental" seemed fair
* Do a little bit of doc restructuring -- I want to do a fuller pass here at some point. In particular, I want to split out a few recommended configurations into their own guides + organize some of the more "advanced" cases to be in another section.
> Update docs to be more explicit about amount of support

- docs/pages/setup.mdx
- package-lock.json
- package.json
We use some `@auth/core` types in our library, but also instruct developers to install `@auth/core`, ant the latest `@auth/core` version has slightly different types.
This adds `@auth/core` as a peer dependency tied to the `0.31` version. Upgrading to a newer `@auth/core` version is something I'll try next.
> Add @auth/core as a peer dependency to prevent version mismatches

- docs/pages/setup.mdx
- package-lock.json
- package.json
Could not go all the way to latest (0.37) easily since it has a major version bump of `oauth4webapi` and requires some pretty non-trivial changes to the portions we forked.
> Update to auth/core 0.36

- docs/pages/api_reference/nextjs/server.mdx
- docs/pages/api_reference/server.mdx
- docs/pages/authz/nextjs.mdx
- package-lock.json
- src/nextjs/server/cookies.ts
- src/nextjs/server/index.tsx
- src/nextjs/server/proxy.ts
- src/nextjs/server/request.ts
- src/nextjs/server/utils.ts
In the current implementation, the cookies we use for Next.js have no expiration which means they're deleted at the end of the browser session (for Chrome, this seems like whenever you quit your browser). A use case where this was particularly disruptive was with mobile web, where closing the app (or maybe even just backgrounding it for long enough) would clear out the cookies.
This PR makes it configurable via an option in `convexAuthNextjsMiddleware`.
In an ideal world, all the configurations would live in one spot (like `auth.ts`), but this is hard in practice since some of the configuration is deployed to Convex while some is deployed to Next.js. It could also be nice to be able to configure this based on a parameter in the sign in request (like the "remember me" check box), but …
> Add configuration for cookie expiration for Next.js

- src/nextjs/server/proxy.ts
- src/nextjs/server/utils.ts
- src/server/implementation/mutations/refreshSession.ts
- src/server/implementation/refreshTokens.ts
- src/server/implementation/sessions.ts
- src/server/implementation/types.ts
- src/server/implementation/utils.ts
- test/convex/sessions.test.ts
- test/package-lock.json
- test/package.json
This updates our reuse detection for refresh tokens as follows:
* refresh tokens track their parent token
* the "active refresh token" is the most recently issued token that has never been used
* If a refresh token has never been used (its `firstUsedTime` is unset), issue a new token + update this tokens `firstUsedTime`
* If a refresh token is the parent of the active refresh token, return the active refresh token (regardless of when this refresh token was first used)
* If a refresh token has been used, but is within the allowed reuse token (10s), issue a new token
* Otherwise, this is an invalid reuse, so mark this token and all its descendants as usable (firstUsedTime 10+s ago)
This is more or less what supabase does for their refresh tokens with a pretty good write up of why …
> Update reuse window implementation

- src/nextjs/server/index.tsx
`NextResponse.next({ request: { headers } })` allows overriding headers on the request. `NextResponse.next({ headers })` initializes those headers on the response itself.
I intended the former but wrote the latter. Amongst other things, I believe this'll fix https://github.com/get-convex/convex-auth/issues/92 for folks with middleware that handles the redirect.
> Fix header propagation in Next.js middleware

- package-lock.json
- package.json
Previously the root package and the test-nextjs package pointed at different versions and I think that was causing the following error:
```
% npm run build
> template-nextjs@0.1.0 build
> next build
▲ Next.js 14.2.5
- Environments: .env.local
Creating an optimized production build ...
⚠ Found lockfile missing swc dependencies, patching...
⚠ Found lockfile missing swc dependencies, patching...
⚠ Found lockfile missing swc dependencies, patching...
⚠ Lockfile was successfully patched, please run "npm install" to ensure @next/swc dependencies are downloaded
✓ Compiled successfully
Linting and checking validity of types  ..Failed to compile.
./components/ui/toggle-group.tsx:28:7
Type error: Type 'React.ReactNode' is not assignable to type …
```
> Update the lock file to point to a common @types/react version

- package-lock.json
- package.json
I think we somehow got away without it with the `@auth/core` dependency masking it (or something). Testing this with `npm pack` + `npx convex dev` reproduced the `Could not resolve "cookie"` issue and this seems to fix it.
> Add missing dependency on cookie

- src/server/implementation/index.ts
- src/server/index.ts
Without this you'd hit an error like:
```
convex/auth.ts:7:39 - error TS2742: The inferred type of 'store' cannot be named without a reference to '../node_modules/@convex-dev/auth/dist/server/implementation/types'. This is likely not portable. A type annotation is necessary.
```
----
> Fix the React (Vite) build when using Convex Auth

- docs/pages/authz.mdx
- docs/pages/config/otps.mdx
- docs/pages/config/passwords.mdx
Add missing `import { useState } from "react";`
and `db.get` returns `Doc` type.
----
> add useState and fix type in docs

- package-lock.json
- package.json
- src/nextjs/server/routeMatcher.ts
- test-nextjs/package-lock.json
Fixes #107.
https://github.com/pillarjs/path-to-regexp/releases/tag/v6.3.0
We'll want to include that this is a potentially breaking change in our release notes, as the version 7.x path-to-regexp that we were using supported more regular expressions in path patterns.
----
> Use a version of path-to-regexp that isn't vulnerable to REDoS

- src/server/oauth/callback.ts
A module resolution error occurs due to no extension on an import from convex-test. Not certain why this is required, but adding an extension to align with the other imports fixes the issue.
Reference discord post: https://discord.com/channels/1019350475847499849/1317446619775373393
----
> fix module resolution error for checks import

- docs/pages/advanced.mdx
- docs/pages/config/oauth/google.mdx
- src/server/implementation/signIn.ts
- src/server/oauth/convexAuth.ts
This will allow a custom domain for signin and callback URLs. OAuth providers like Google (which show the domain) will use this instead of showing `happy-animal-123.convex.site` in the OAuth consent screen.
This should help to resolve https://github.com/get-convex/convex-auth/issues/53.
----
> A couple tweaks to allow a CUSTOM_AUTH_SITE_URL

- CHANGELOG.md
- package-lock.json
- src/nextjs/server/index.tsx
- test-nextjs/package-lock.json
Make the Next.js middleware function `isAuthenticated` fail more loudly. Previously it returned false in the case of a Convex backend that didn't expose an endpoint called `auth:isAuthenticated`, now it throws an error. This should help people with the migration required for 0.0.76.
> Make isAuthenticated in middleware fail more loudly.

- docs/pages/setup.mdx
Fixes #114 
In Expo (React Native), providing `storage={secureStorage}` to `ConvexAuthProvider` makes the web version of the app crashes (see #114). Checking the platform and only assign `secureStorage` on Android and iOS fixes this issue.
----
> Add platform check for ConvexAuthProvider's storage

- src/server/implementation/index.ts
- src/server/index.ts
Expose unstable but useful function reference types for return values of auth(), requested by implementors of other clients.
Resolves #132
> Expose function reference types for return values of auth()

- .gitignore
- src/react/client.tsx
Fixes #147 
When running Convex Auth in a React Native app, when the app is in the background for a long enough period of time, upon reopening:
- the app is in the same visual state it was when backgrounded
- it is no longer connected to Convex
- `isAuthenticated` is true and `<Authenticated>` renders children
- there are no signs of errors, except new or modified queries fail to load and mutations do nothing, although optimistic updates apply and stay in place indefinitely
- Run Convex Auth in an Expo app (I've only tried with iOS on device, not certain about Android or simulator)
- After loading app, move it to the background
- Wait for the minimum JWT duration to pass (an hour by default, I dropped to 10s for testing)
- Bring app back to foreground
Convex Auth uses a mutex to run …
> fix auth refresh silent failure for react native

- docs/pages/config/oauth/apple.mdx
The client secret from Sign In with Apple is a JWT that must expire in less than 6 months. The
generator on the website generates tokens expiring in 6 months, but we’re not documenting it at
the moment. This can cause existing installations to break, so we should document it so that
users rotate their client secrets.
> Document the Sign In with Apple secret expiration

- docs/pages/config/otps.mdx
On strict type checking with a tool like Biome, the presence of `async` keyword results in an error
`This async function lacks an await expression`
This happens because of the `async` keyword in `async generateVerificationToken()`;
The `generateRandomString` from `oslo/crypto` package is not asynchronous.
> Update OTP Documentation

- src/cli/index.ts
- test/convex/auth.ts
If this is run in a non-interactive terminal, accept the defaults (or crash if there's no safe default) instead of just hanging.
> [cli] Run without prompts if in a non-interactive environment

- src/nextjs/server/index.tsx
- src/nextjs/server/proxy.ts
- src/nextjs/server/request.ts
- src/nextjs/server/utils.ts
In https://github.com/get-convex/convex-js/commit/3183379af8bdc2a525877818b9198b4dee6955e3 we guard against passing `url: undefined` to a `convex/nextjs` function, primarily to guard against things like `{ url: process.env.VAR_I_DIDNT_SET }` quietly falling back on the default `NEXT_PUBLIC_CONVEX_URL`.
However, we were passing through the optional `convexUrl` property, resulting in `{ url: undefined }` and crashing the Convex Auth related Next.js functions.
This adds a `getConvexNextjsOptions` that takes the relevant configuration for Convex Auth + Next.js (right now just `convexUrl`) and transforms it into the options for `fetchQuery` and friends.
I searched for imports for `convex/nextjs` and updated all of these to use this helper (also fixing multiple spots where we weren't respecting …
> Fix handling of URL with convex/nextjs functions

- docs/pages/setup/manual.mdx
when following the guide, I got this error:
```
webdevcody:~/Workspace/site-sensei$ node generateKeys.mjs
file:///Users/webdevcody/Workspace/site-sensei/node_modules/jose/dist/webapi/lib/asn1.js:20
throw new TypeError('CryptoKey is not extractable');
^
TypeError: CryptoKey is not extractable
at genericExport (file:///Users/webdevcody/Workspace/site-sensei/node_modules/jose/dist/webapi/lib/asn1.js:20:15)
at toPKCS8 (file:///Users/webdevcody/Workspace/site-sensei/node_modules/jose/dist/webapi/lib/asn1.js:31:12)
at exportPKCS8 (file:///Users/webdevcody/Workspace/site-sensei/node_modules/jose/dist/webapi/key/export.js:7:12)
at file:///Users/webdevcody/Workspace/site-sensei/generateKeys.mjs:4:26
Node.js v20.16.0
```
adding this to the generateKeyPair method seemed to fix it... I'm guessing …
> Latest version of Jose fails with this example code

- docs/pages/config/otps.mdx
Now that Resend 3.5 has been released more than 9 months ago, I think it’s fine just asking people to `npm i resend`.
> Remove Resend version warning

- package-lock.json
- package.json
- test-nextjs/package-lock.json
- test/package-lock.json
We’re not using `arctic` so it’s safe to remove.
> Remove the dependency on `arctic`

- docs/pages/setup.mdx
Adding missing impor for react native setup in the `setup.mdx` file
This pull request updates the documentation to reflect the correct usage of the `ConvexAuthProvider` component from the `@convex-dev/auth/react` package, replacing the older `ConvexProvider` from `convex/react`.
Documentation updates:
* [`docs/pages/setup.mdx`](diffhunk://#diff-3c922c2063f438e0a8a6e8e6e44a9e4a24fd0522f6c0886f85d93efe404fd17fR283): Updated the example code to import `ConvexAuthProvider` instead of `ConvexProvider` and added an import for `Platform` from `react-native` to align with the updated example.
----
> Add missing Platform import for React Native setup

- src/nextjs/client.tsx
- src/nextjs/server/proxy.ts
- src/nextjs/server/utils.ts
Fixes #103
Smaller scope alternative to #194
When Convex Auth runs from a react client (non-server), the sign in action throws on invalid input, eg., missing or invalid password. The nextjs auth api proxy swallows the error and returns a 200 response with a null body.
This solution:
- Returns a 400 with an `error` key in the body containing the error message (complete with stack trace, mirroring the non-next react behavior)
- Parses and throws the error in the nextjs authenticated function, which is only used for signIn and signOut
- Avoids changes outside of the immediately affected code paths (no react client changes)
Should we be throwing a stack trace? Maybe not. But the current nextjs behavior is a bug, and this solution matches what we already do intentionally for non nextjs apps. …
> match Convex Action error handling in nextjs api proxy

- docs/pages/config/passwords.mdx
`setStep` is defined like this:
```
const [step, setStep] = useState<"forgot" | { email: string }>("forgot");
```
But we try to set the step to `signIn` like this:
```
<button type="button" onClick={() => setStep("signIn")}>
```
And we get this error:
```
Argument of type '"signIn"' is not assignable to parameter of type 'SetStateAction<"forgot" | { email: string; }>'
```
So I just fixed the small mistake by changing `setStep("signIn")` to `setStep("forgot")`.
Hope this helps :)
----
> Fix error in password reset form

- src/react/client.tsx
Despite being deprecated and defined in specs as "returning 'Gecko' in all browsers", going with checking `navigator.product`.
- It's the only explicit way to check for the RN/Expo environment
- The React Native devs have kept this defined consistently since at least 2018 ([source](https://github.com/facebook/react-native/blob/a7810f6995f72f86605f8661992557f295146af6/packages/react-native/Libraries/Core/setUpNavigator.js#L18))
- Expo co-founder James Ide backed it ([source](https://github.com/facebook/react-native/issues/10881#issuecomment-261392494))
- Axios uses it ([source](https://github.com/axios/axios/blob/c7e0fea78716e86694d5023f8f17d174bf064e8a/lib/platform/common/utils.js#L5-L23))
There's no right way to do this, but I really don't want devs to have to go set a prop for this …
> add explicit react native check

- docs/pages/config/passwords.mdx
The `profile`  function takes a second ctx parameter which the docs did not include.
Additionally, it was not clear what to do with this new `Password` object, I added a line to make that clearer.
----
> Improve Custom User Schema Creation Docs

- docs/pages/config/otps.mdx
- docs/pages/config/passwords.mdx
- package-lock.json
- package.json
- src/server/implementation/mutations/userOAuth.ts
- src/server/implementation/signIn.ts
- src/server/implementation/utils.ts
- test-nextjs/package-lock.json
- test-router/convex/otp/FakePhone.ts
- test-router/convex/otp/ResendOTP.ts
- test-router/convex/passwordReset/ResendOTPPasswordReset.ts
- test-router/package.json
- test/convex/otp/FakePhone.ts
- test/convex/otp/ResendOTP.ts
- test/convex/otp/TwilioOTP.ts
- test/convex/passwordReset/ResendOTPPasswordReset.ts
- test/package-lock.json
- test/package.json
This removes our usage of the [deprecated](https://www.npmjs.com/package/oslo) `oslo/*` packages and replaces them with their `@oslojs/*` alternatives.
> Migrate from `oslo` to `@oslojs`
